# Generated by Django 5.0.1 on 2024-08-26 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Наименование')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Конкурс',
                'verbose_name_plural': 'Конкурсы',
            },
        ),
        migrations.CreateModel(
            name='Document_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Наименование')),
                ('requirements', models.BooleanField(verbose_name='Обязательный')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Наименование проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания обращения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('custom_data', models.JSONField(default=dict, verbose_name='Кастомные поля')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.locality', verbose_name='Населенный пункт')),
                ('municipal_district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.municipal_district', verbose_name='Район')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.settlement', verbose_name='Поселение')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constructor.contest', verbose_name='Конкурс')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания обращения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constructor.application', verbose_name='Заявка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_urls', models.JSONField(default=list, verbose_name='Ссылки на файлы')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constructor.document_type', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания обращения')),
                ('text', models.TextField(verbose_name='Текст')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constructor.application', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
            },
        ),
        migrations.CreateModel(
            name='Project_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Наименование')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constructor.contest', verbose_name='Конкурс')),
            ],
            options={
                'verbose_name': 'Типология проекта',
                'verbose_name_plural': 'Типологии проектов',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='project_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constructor.project_type', verbose_name='Типология проекта'),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Наименование')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constructor.contest', verbose_name='Конкурс')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constructor.status', verbose_name='Статус'),
        ),
    ]
