# Generated by Django 5.0.1 on 2024-08-26 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Коммент', 'verbose_name_plural': 'Комменты'},
        ),
    ]
