# Generated by Django 5.0.1 on 2024-08-27 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0003_remove_project_type_contest_remove_status_contest_and_more'),
        ('profiles', '0009_section_remove_profile_contest_profile_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Наименование')),
                ('propherties', models.JSONField(default=dict, verbose_name='')),
                ('required', models.JSONField(default=list, verbose_name='')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Схема',
                'verbose_name_plural': 'Схемы',
            },
        ),
    ]
