# Generated by Django 5.0.1 on 2024-08-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0004_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='propherties',
            field=models.JSONField(default=dict, verbose_name='Properties'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='required',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Required'),
        ),
    ]
