# Generated by Django 5.0.1 on 2024-08-27 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0005_alter_schema_propherties_alter_schema_required'),
        ('profiles', '0009_section_remove_profile_contest_profile_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='profiles.section', verbose_name='Секция'),
        ),
    ]
