# Generated by Django 5.0.1 on 2024-08-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0006_alter_schema_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='type',
            field=models.CharField(default=1, max_length=120, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
