# Generated by Django 5.0.1 on 2024-08-27 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0007_schema_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schema',
            old_name='propherties',
            new_name='properties',
        ),
    ]
