# Generated by Django 5.0.1 on 2024-08-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0008_rename_propherties_schema_properties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_table_fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Наименование')),
            ],
        ),
    ]
