# Generated by Django 5.0.1 on 2024-08-28 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0010_alter_main_table_fields_options_and_more'),
        ('profiles', '0010_section_header_section_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_table_fields',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='profiles.section', verbose_name='Секция'),
        ),
    ]
