# Generated by Django 5.0.1 on 2024-08-29 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0011_alter_main_table_fields_section'),
        ('profiles', '0010_section_header_section_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_table_fields',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.section', verbose_name='Секция'),
        ),
    ]
