# Generated by Django 5.0.1 on 2024-08-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0012_alter_main_table_fields_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_table_fields',
            name='pos',
            field=models.PositiveIntegerField(default=100, verbose_name='Позиция'),
        ),
    ]
