# Generated by Django 5.0.1 on 2024-08-30 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0013_main_table_fields_pos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='section',
        ),
        migrations.AddField(
            model_name='document',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='constructor.application', verbose_name='Заявка'),
            preserve_default=False,
        ),
    ]
