# Generated by Django 5.0.1 on 2024-08-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0014_remove_document_section_document_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='grant_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Сумма гранта'),
        ),
    ]
