# Generated by Django 5.0.1 on 2024-09-02 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0015_contest_grant_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='active',
        ),
    ]
