# Generated by Django 5.0.1 on 2024-09-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0016_remove_contest_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('opened', 'Идет прием заявок'), ('tech_work', 'Идут подготовительные работы'), ('check', 'Идет проверка'), ('on_exam', 'Идет независимая экспертиза'), ('closed', 'Конкурс завершен')], default='new', max_length=120, verbose_name='Статус'),
        ),
    ]
