# Generated by Django 5.0.1 on 2024-09-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0017_contest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='grant_sum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Сумма гранта'),
        ),
    ]
