# Generated by Django 5.0.1 on 2024-09-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0018_alter_contest_grant_sum'),
        ('locations', '0006_remove_locality_type_abbreviation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contest_type',
            field=models.ManyToManyField(to='locations.settlement_type'),
        ),
    ]
