# Generated by Django 5.0.1 on 2024-09-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0019_contest_contest_type'),
        ('locations', '0006_remove_locality_type_abbreviation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='contest_type',
        ),
        migrations.AddField(
            model_name='contest',
            name='contest_types',
            field=models.ManyToManyField(help_text='Для кого этот конкурс', to='locations.settlement_type', verbose_name='Для кого'),
        ),
    ]
