# Generated by Django 5.0.1 on 2024-09-04 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0020_remove_contest_contest_type_contest_contest_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document_type',
            old_name='requirements',
            new_name='required',
        ),
    ]
