# Generated by Django 5.0.1 on 2024-09-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0021_rename_requirements_document_type_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='application',
        ),
        migrations.AddField(
            model_name='application',
            name='documents',
            field=models.JSONField(default=list, verbose_name='Документы'),
        ),
    ]
