# Generated by Django 5.0.1 on 2024-09-04 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0022_remove_document_application_application_documents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
