# Generated by Django 5.0.1 on 2024-09-05 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0023_delete_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
