# Generated by Django 5.0.1 on 2024-09-12 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0025_historicalapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalapplication',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'История', 'verbose_name_plural': 'historical Заявки'},
        ),
    ]
