# Generated by Django 5.0.1 on 2024-09-13 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0026_alter_historicalapplication_options'),
        ('profiles', '0016_roles_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main_table_fields',
            options={'verbose_name': 'Отображаемое значение в главной таблице', 'verbose_name_plural': 'Отображаемые значения в главной таблице'},
        ),
        migrations.CreateModel(
            name='Custom_validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Наименование')),
                ('code', models.TextField(verbose_name='Код')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Кастомное валидирование',
                'verbose_name_plural': 'Кастомные валидации',
            },
        ),
    ]
