# Generated by Django 5.0.1 on 2024-09-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0027_alter_main_table_fields_options_custom_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='application',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='custom_validation',
            name='code',
            field=models.TextField(default='#python!\n# imported models Application, Profile\ncurrent_user = request.user\ncurrent_contest = get_current_contest(request)\nprofile_type = Profile.objects.get(user=current_user).profile_type\n', verbose_name='Код'),
        ),
    ]
