# Generated by Django 5.0.1 on 2024-09-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0028_application_latitude_application_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='year',
            field=models.PositiveIntegerField(default=2024, verbose_name='Год проведения'),
            preserve_default=False,
        ),
    ]
