# Generated by Django 5.0.1 on 2024-09-23 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0029_contest_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='application',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='historicalapplication',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='historicalapplication',
            name='longitude',
        ),
    ]
