# Generated by Django 5.0.1 on 2024-09-23 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0030_remove_application_latitude_and_more'),
        ('locations', '0006_remove_locality_type_abbreviation_and_more'),
        ('profiles', '0019_alter_section_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='application',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='constructor.contest', verbose_name='Конкурс'),
        ),
        migrations.AlterField(
            model_name='application',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='locations.locality', verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='application',
            name='municipal_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='locations.municipal_district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='application',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='profiles.section', verbose_name='Секция'),
        ),
        migrations.AlterField(
            model_name='application',
            name='settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='locations.settlement', verbose_name='Поселение'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='constructor.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='status',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='constuctor_statuses', to='profiles.section', verbose_name='Секция'),
        ),
    ]
