# Generated by Django 5.0.1 on 2024-09-23 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0031_alter_application_author_alter_application_contest_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_table_fields',
            name='contest_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='Приложение'),
            preserve_default=False,
        ),
    ]
