# Generated by Django 5.0.1 on 2024-09-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0032_main_table_fields_contest_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_table_fields',
            old_name='contest_type',
            new_name='content_type',
        ),
    ]
