# Generated by Django 5.0.1 on 2024-09-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0033_rename_contest_type_main_table_fields_content_type'),
        ('locations', '0007_district_type_alter_municipal_district_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contest_types2',
            field=models.ManyToManyField(help_text='Для кого этот конкурс 2', to='locations.district_type', verbose_name='Для кого 2'),
        ),
    ]
