# Generated by Django 5.0.1 on 2024-09-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0034_contest_contest_types2'),
        ('locations', '0007_district_type_alter_municipal_district_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='contest_types',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='contest_types2',
        ),
        migrations.AddField(
            model_name='contest',
            name='district_type',
            field=models.ManyToManyField(help_text='Для кого этот конкурс', to='locations.district_type', verbose_name='Для кого'),
        ),
    ]
