# Generated by Django 5.0.1 on 2024-09-24 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0035_remove_contest_contest_types_and_more'),
        ('profiles', '0022_remove_profile_profile_district_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='profiles.profile', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='author',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='profiles.profile', verbose_name='Пользователь'),
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
