# Generated by Django 5.0.1 on 2024-09-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0036_alter_application_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_validation',
            name='code',
            field=models.TextField(default='#python!\n# imported models Application, Profile\ncurrent_user = request.user\ncurrent_contest = get_current_contest(request)\nprofile_type = request.user.profile.profile_type\n', verbose_name='Код'),
        ),
    ]
