# Generated by Django 5.0.1 on 2024-10-09 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0039_historicalcontest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='constructor.project_type', verbose_name='Типология проекта'),
        ),
    ]
