# Generated by Django 5.0.1 on 2024-10-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0041_status_tech_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_type',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Наименование'),
        ),
    ]
