# Generated by Django 5.0.1 on 2024-10-24 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0042_alter_project_type_title'),
        ('locations', '0009_historicallocality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='locations.locality', verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='application',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='locations.settlement', verbose_name='Поселение'),
        ),
    ]
