# Generated by Django 5.0.1 on 2024-11-11 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0045_status_roles'),
        ('profiles', '0037_section_tech_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_set', to='profiles.roles'),
        ),
        migrations.CreateModel(
            name='Calculated_fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Наименование')),
                ('code', models.TextField(verbose_name='Код')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Вычисляемое поле',
                'verbose_name_plural': 'Вычисляемые поля',
            },
        ),
    ]
