# Generated by Django 5.0.1 on 2024-11-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0047_schema_contests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='contests',
            field=models.ManyToManyField(blank=True, to='constructor.contest', verbose_name='Конкурсы'),
        ),
    ]
