# Generated by Django 5.0.1 on 2024-11-26 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0049_calculated_fields_field_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculated_fields',
            name='field_type',
        ),
    ]
