# Generated by Django 5.0.1 on 2024-11-26 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0051_calculated_fields_field_type'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculated_fields',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculated_fields',
            name='use_sum',
            field=models.BooleanField(default=False, verbose_name='Использовать SUM'),
        ),
    ]
