# Generated by Django 5.0.1 on 2024-11-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0052_calculated_fields_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculated_fields',
            name='func_type',
            field=models.IntegerField(choices=[(1, 'annotate'), (2, 'aggregate')], default=1, verbose_name='Тип метода'),
        ),
    ]
