# Generated by Django 5.0.1 on 2024-02-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contest',
            field=models.CharField(choices=[('65a766112e0fe1554e0d3c99', 'Тестовый конкурс'), ('65a767c72e0fe1554e0d3c9a', 'Конкурс для СМИ')], default=1, max_length=120, verbose_name='Конкурс'),
            preserve_default=False,
        ),
    ]
