# Generated by Django 5.0.1 on 2024-02-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contest',
            field=models.CharField(choices=[('1', 'Основное общее'), ('2', 'Среднее общее'), ('3', 'Среднее профессиональное'), ('4', 'Высшее'), ('5', 'Иное')], max_length=120, verbose_name='Конкурс'),
        ),
    ]
