# Generated by Django 5.0.1 on 2024-08-26 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_settlement_population'),
        ('profiles', '0006_alter_profile_contest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contest',
        ),
        migrations.AddField(
            model_name='profile',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.locality', verbose_name='Населенный пункт'),
        ),
        migrations.AddField(
            model_name='profile',
            name='municipal_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.municipal_district', verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='profile',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.settlement', verbose_name='Поселение'),
        ),
    ]
