# Generated by Django 5.0.1 on 2024-09-03 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_locality_latitude_locality_longitude'),
        ('profiles', '0010_section_header_section_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.settlement_type', verbose_name='Тип профиля'),
        ),
    ]
