# Generated by Django 5.0.1 on 2024-09-05 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_profile_profile_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role_handler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_point_name', models.TextField(verbose_name='Название')),
                ('role', models.ManyToManyField(to='profiles.roles', verbose_name='Роли')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_handler_section', to='profiles.roles', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Доступ к методу',
                'verbose_name_plural': 'Доступы к методам',
            },
        ),
    ]
