# Generated by Django 5.0.1 on 2024-09-05 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_role_handler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role_handler',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.section', verbose_name='Раздел'),
        ),
    ]
