# Generated by Django 5.0.1 on 2024-09-05 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_role_handler_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role_handler',
            old_name='role',
            new_name='roles',
        ),
    ]
