# Generated by Django 5.0.1 on 2024-09-09 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_remove_role_handler_end_point_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='profiles.section', verbose_name='Раздел'),
            preserve_default=False,
        ),
    ]
