# Generated by Django 5.0.1 on 2024-09-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_profile_email_profile_fio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='logo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на лого'),
        ),
    ]
