# Generated by Django 5.0.1 on 2024-09-24 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_district_type_alter_municipal_district_options_and_more'),
        ('profiles', '0020_profile_profile_type_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_type_2',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_district_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.district_type', verbose_name='Тип профиля'),
        ),
    ]
