# Generated by Django 5.0.1 on 2024-09-24 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_remove_profile_profile_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_district_type',
        ),
    ]
