# Generated by Django 5.0.1 on 2024-09-25 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
