# Generated by Django 5.0.1 on 2024-09-26 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_remove_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fio',
        ),
    ]
