# Generated by Django 5.0.1 on 2024-10-07 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_profile_allowed_number_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Наименование')),
                ('abbreviation', models.CharField(max_length=10, verbose_name='Аббревиатура')),
            ],
            options={
                'verbose_name': 'Тип профиля',
                'verbose_name_plural': 'Типы профилей',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.profile_type', verbose_name='Тип профиля'),
        ),
    ]
