# Generated by Django 5.0.1 on 2024-10-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_profile_type_alter_profile_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(default=123, max_length=120, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
