# Generated by Django 5.0.1 on 2024-10-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_type',
            name='abbreviation',
            field=models.CharField(max_length=120, verbose_name='Описание'),
        ),
    ]
