# Generated by Django 5.0.1 on 2024-10-23 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0034_alter_profile_type_abbreviation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='section',
        ),
    ]
