# Generated by Django 5.0.1 on 2024-11-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0036_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='tech_name',
            field=models.CharField(default=1, max_length=120, verbose_name='Тех. название'),
            preserve_default=False,
        ),
    ]
