# Generated by Django 5.0.1 on 2024-11-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0037_section_tech_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(max_length=320, verbose_name='Имя'),
        ),
    ]
