# Generated by Django 5.0.1 on 2024-12-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0039_section_amount_of_subsidy_section_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='adt',
            field=models.TextField(blank=True, null=True, verbose_name='Объявление'),
        ),
    ]
