# Generated by Django 5.0.1 on 2024-10-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_verificationcode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True, verbose_name='эл. почта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='email',
            field=models.EmailField(db_index=True, default=1, max_length=254, verbose_name='эл. почта'),
            preserve_default=False,
        ),
    ]
