# Generated by Django 5.0.1 on 2024-09-24 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_alter_meeting_app_author_alter_meeting_app_contest_and_more'),
        ('profiles', '0022_remove_profile_profile_district_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting_app',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='profiles.profile', verbose_name='Пользователь'),
        ),
    ]
