# Generated by Django 5.0.1 on 2024-10-24 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_historicallocality'),
        ('meeting', '0007_alter_status_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting_app',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='locations.locality', verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='meeting_app',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='locations.settlement', verbose_name='Поселение'),
        ),
    ]
