# Generated by Django 5.0.1 on 2024-11-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0048_alter_schema_contests'),
        ('meeting', '0011_meeting_app_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting_schema',
            name='contests',
            field=models.ManyToManyField(blank=True, to='constructor.contest', verbose_name='Конкурсы'),
        ),
    ]
