# Generated by Django 5.0.1 on 2024-09-06 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_alter_meeting_app_contest_meeting_document_type'),
        ('profiles', '0014_rename_role_role_handler_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting_status',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='profiles.section', verbose_name='Секция'),
            preserve_default=False,
        ),
    ]
