version: "3.0"
   
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
      - ./logs:/app/logs
    env_file:
      - ./.env
    ports:
      - "8001:8001"
