version: '3'

services:
  db:
    image: postgres:12
    container_name: my_custom_postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432-5432"

  web:
    container_name: my_custom_web
    build: .
    command: /bin/bash -c "
      echo -e 'SECRET_KEY=for_github_test\\nDB_NAME=mydb\\nDB_USER=myuser\\nDB_PASSWORD=mypassword\\nDB_HOST=localhost\\nDB_PORT=5432\\nDEBUG=False\\nCONTEST_URL=http://127.0.0.1:8000'\\nredis=redis://127.0.0.1:6379/0 > /code/.env &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - ./logs:/app/logs
    working_dir: /code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mydb
      - DB_USER=myuser
      - DB_PASSWORD=mypassword

volumes:
  db_data:
