# Generated by Django 5.0.1 on 2024-08-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='code',
            field=models.TextField(default='', verbose_name='Код'),
        ),
    ]
