# Generated by Django 5.0.1 on 2024-08-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0002_formula_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='code',
            field=models.TextField(default='#python!\n# result - пустой dict\n# self.get_financing_settlement_budget() - Бюджет поселения (муниципального района)\n# self.get_financing_people() - Население (поступления от жителей)\n# self.get_financing_sponsors() - Спонсоры\n# self.get_financing_republic_grant() - Субсидия из бюджета Республики Саха (Якутия)\n# self.total_price() - Общая сумма\n# key - названия поля\n# value - значение поля\nresult[key] =\n', verbose_name='Код'),
        ),
    ]
