# Generated by Django 5.0.1 on 2024-12-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0006_formula_contest_alter_formula_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula',
            name='code',
        ),
        migrations.AddField(
            model_name='formula',
            name='json',
            field=models.JSONField(blank=True, null=True, verbose_name='Формула'),
        ),
    ]
