# Generated by Django 5.0.1 on 2024-09-30 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0030_alter_profile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles_manager_app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('status', models.CharField(choices=[('1', 'Создано'), ('2', 'Выполнено'), ('3', 'Отклонено')], default='Создано', max_length=40, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Профиль')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Заявка на перенос профиля',
                'verbose_name_plural': 'Заявки на перенос профиля',
            },
        ),
    ]
