# Generated by Django 5.0.1 on 2024-09-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles_manager_app',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
