# Generated by Django 5.0.1 on 2024-10-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_manager', '0002_alter_profiles_manager_app_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles_manager_app',
            name='status',
            field=models.IntegerField(choices=[(1, 'Создано'), (2, 'Выполнено'), (3, 'Отклонено')], default=1, verbose_name='Статус'),
        ),
    ]
