# Generated by Django 5.0.1 on 2024-11-18 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_alter_historicallocality_locnamee_and_more'),
        ('profiles', '0038_alter_profile_title'),
        ('profiles_manager', '0003_alter_profiles_manager_app_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles_manager_app',
            name='custom_locality',
            field=models.TextField(blank=True, null=True, verbose_name='Кастомный населенный пункт'),
        ),
        migrations.AddField(
            model_name='profiles_manager_app',
            name='municipal_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.municipal_district'),
        ),
        migrations.AddField(
            model_name='profiles_manager_app',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.settlement'),
        ),
        migrations.AlterField(
            model_name='profiles_manager_app',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Профиль'),
        ),
    ]
