# Generated by Django 5.0.1 on 2024-10-11 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constructor', '0040_alter_application_project_type'),
        ('locations', '0009_historicallocality'),
        ('profiles', '0034_alter_profile_type_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mo_report_document_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Наименование')),
                ('required', models.BooleanField(verbose_name='Обязательный')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
            },
        ),
        migrations.CreateModel(
            name='Mo_report_schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Наименование')),
                ('properties', models.JSONField(default=dict, verbose_name='Properties')),
                ('required', models.JSONField(blank=True, default=list, null=True, verbose_name='Required')),
                ('type', models.CharField(max_length=120, verbose_name='Тип')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='profiles.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Схема',
                'verbose_name_plural': 'Схемы',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Наименование')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mo_report_statuses', to='profiles.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Mo_report_app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания обращения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('custom_data', models.JSONField(default=dict, verbose_name='Кастомные поля')),
                ('documents', models.JSONField(default=list, verbose_name='Документы')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mo_report_app', to='constructor.application', verbose_name='Заявление')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='profiles.profile', verbose_name='Пользователь')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='constructor.contest', verbose_name='Конкурс')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='locations.locality', verbose_name='Населенный пункт')),
                ('municipal_district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='locations.municipal_district', verbose_name='Район')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='profiles.section', verbose_name='Секция')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='locations.settlement', verbose_name='Поселение')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='mo_report.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Отчет МО',
                'verbose_name_plural': 'Отчеты МО',
            },
        ),
    ]
