# Generated by Django 5.0.1 on 2024-09-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book', '0003_phone_book_ip_phone_alter_phone_book_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone_book',
            name='ip_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
    ]
