# Generated by Django 5.0.1 on 2024-10-10 01:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book', '0004_alter_phone_book_ip_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone_book',
            name='phone',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
