# Generated by Django 5.0.1 on 2024-10-10 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book', '0006_alter_phone_book_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone_book',
            name='phone',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{1,4}[-]?\\d{1,4}[-]?\\d{1,4}[-]?\\d{1,4}$')]),
        ),
    ]
