# Generated by Django 5.0.1 on 2024-10-10 07:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book', '0010_alter_phone_book_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone_book',
            name='ip_phone',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(regex='^[\\d\\-\\+]+$')], verbose_name='ip Телефон'),
        ),
        migrations.AlterField(
            model_name='phone_book',
            name='phone',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(regex='^[\\d\\-\\+]+$')], verbose_name='Телефон'),
        ),
    ]
