# Generated by Django 5.0.1 on 2024-10-17 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_created_at'),
        ('profiles', '0034_alter_profile_type_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.section', verbose_name='Секция'),
            preserve_default=False,
        ),
    ]
