# Generated by Django 5.0.1 on 2024-08-26 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locality_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип населенного пункта',
                'verbose_name_plural': 'Типы населенных пунктов',
            },
        ),
        migrations.CreateModel(
            name='Municipal_district',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegionName', models.TextField(verbose_name='Полное наименование')),
                ('RegionNameE', models.CharField(max_length=120, verbose_name='Наименование')),
                ('OKTMO', models.CharField(max_length=120, verbose_name='ОКТМО')),
                ('Population', models.PositiveIntegerField(verbose_name='Население')),
                ('RegOKTMO', models.CharField(verbose_name='ОКТМО региона')),
                ('RegIsNorthern', models.BooleanField(verbose_name='Северный регион')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Settlement_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип поселения',
                'verbose_name_plural': 'Типы поселений',
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MunicName', models.TextField(verbose_name='Полное наименование')),
                ('MunicNameE', models.CharField(max_length=120, verbose_name='Наименование')),
                ('Population', models.PositiveIntegerField(verbose_name='Население')),
                ('OKTMO', models.CharField(max_length=120, verbose_name='ОКТМО')),
                ('OKATO', models.CharField(max_length=120, verbose_name='ОКАТО')),
                ('RegID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.municipal_district', verbose_name='Регион')),
                ('MunicTypeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.settlement_type', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Поселение',
                'verbose_name_plural': 'Поселения',
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OKTMO', models.CharField(max_length=120, verbose_name='ОКТМО')),
                ('LocName', models.TextField(verbose_name='Полное наименование')),
                ('LocNameE', models.CharField(max_length=120, verbose_name='Наименование')),
                ('LocPopulation', models.PositiveIntegerField(verbose_name='Население')),
                ('LocTypeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.locality_type', verbose_name='Тип')),
                ('RegID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.municipal_district', verbose_name='Регион')),
                ('MunicID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.settlement', verbose_name='Поселение')),
            ],
            options={
                'verbose_name': 'Населенный пункт',
                'verbose_name_plural': 'Населенные пункты',
            },
        ),
    ]
