# Generated by Django 5.0.1 on 2024-08-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='Population',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Население'),
        ),
    ]
