# Generated by Django 5.0.1 on 2024-09-03 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_settlement_population'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region_center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.locality', verbose_name='Населенный пункт')),
                ('municipal_district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.municipal_district', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Центр района',
                'verbose_name_plural': 'Центры районов',
            },
        ),
    ]
