# Generated by Django 5.0.1 on 2024-09-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_region_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='Latitude',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='locality',
            name='Longitude',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Долгота'),
        ),
    ]
