# Generated by Django 5.0.1 on 2024-09-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_locality_latitude_locality_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality_type',
            name='abbreviation',
            field=models.CharField(default=1, max_length=10, verbose_name='Аббревиатура'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locality_type',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Наименование'),
        ),
    ]
