# Generated by Django 5.0.1 on 2024-09-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_locality_type_abbreviation_alter_locality_type_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locality_type',
            name='abbreviation',
        ),
        migrations.AddField(
            model_name='settlement_type',
            name='abbreviation',
            field=models.CharField(default=1, max_length=10, verbose_name='Аббревиатура'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settlement_type',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Наименование'),
        ),
    ]
