# Generated by Django 5.0.1 on 2024-09-24 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_remove_locality_type_abbreviation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип района',
                'verbose_name_plural': 'Типы районов',
            },
        ),
        migrations.AlterModelOptions(
            name='municipal_district',
            options={'verbose_name': 'Район', 'verbose_name_plural': 'Районы'},
        ),
        migrations.AddField(
            model_name='municipal_district',
            name='district_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='locations.district_type', verbose_name='Тип района'),
            preserve_default=False,
        ),
    ]
