# Generated by Django 5.0.1 on 2024-09-25 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_district_type_alter_municipal_district_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipal_district',
            name='district_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.district_type', verbose_name='Тип района'),
        ),
    ]
