# Generated by Django 5.0.1 on 2024-10-10 01:15

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_alter_municipal_district_district_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLocality',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('OKTMO', models.CharField(max_length=120, verbose_name='ОКТМО')),
                ('LocName', models.TextField(verbose_name='Полное наименование')),
                ('LocNameE', models.CharField(max_length=120, verbose_name='Наименование')),
                ('LocPopulation', models.PositiveIntegerField(verbose_name='Население')),
                ('Latitude', models.CharField(blank=True, max_length=120, null=True, verbose_name='Широта')),
                ('Longitude', models.CharField(blank=True, max_length=120, null=True, verbose_name='Долгота')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('LocTypeID', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.locality_type', verbose_name='Тип')),
                ('MunicID', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.settlement', verbose_name='Поселение')),
                ('RegID', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.municipal_district', verbose_name='Регион')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'historical Населенные пункты',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
