# Generated by Django 5.0.1 on 2024-11-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_historicallocality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallocality',
            name='LocNameE',
            field=models.CharField(max_length=320, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='LocNameE',
            field=models.CharField(max_length=320, verbose_name='Наименование'),
        ),
    ]
