# Generated by Django 5.0.1 on 2024-11-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_alter_historicallocality_locnamee_and_more'),
        ('profiles', '0038_alter_profile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='sections',
            field=models.ManyToManyField(blank=True, to='profiles.section'),
        ),
    ]
