# Generated by Django 5.0.1 on 2024-09-06 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0024_delete_comments'),
        ('meeting', '0001_initial'),
        ('profiles', '0014_rename_role_role_handler_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting_app',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constructor.contest', verbose_name='Конкурс'),
        ),
        migrations.CreateModel(
            name='Meeting_document_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Наименование')),
                ('required', models.BooleanField(verbose_name='Обязательный')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
            },
        ),
    ]
