# Generated by Django 5.0.1 on 2024-08-30 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0004_remove_formula_coefficent_remove_formula_formula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula',
            name='field',
        ),
    ]
