# Generated by Django 5.0.1 on 2024-09-09 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='faq.question', verbose_name='Вопрос'),
        ),
    ]
