# Generated by Django 5.0.1 on 2024-09-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_alter_answer_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(default=1, verbose_name='Ответ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.TextField(default=1, verbose_name='Вопрос'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
