# Generated by Django 5.0.1 on 2024-09-19 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0005_alter_question_author_alter_question_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
    ]
