# Generated by Django 5.0.1 on 2024-02-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api_getaway_mappping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название микросервиса')),
                ('url', models.URLField(verbose_name='Url')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Маршрут апи',
                'verbose_name_plural': 'Маршруты апи',
            },
        ),
    ]
