# Generated by Django 5.0.1 on 2024-02-09 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_getaway', '0002_remaining_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='remaining_paths',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api_getaway.api_getaway_mappping', verbose_name='Сервис'),
            preserve_default=False,
        ),
    ]
