# Generated by Django 5.0.1 on 2024-09-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='text',
        ),
        migrations.AddField(
            model_name='history',
            name='diff',
            field=models.JSONField(blank=True, null=True, verbose_name='Отличия'),
        ),
    ]
