# Generated by Django 5.0.1 on 2024-09-30 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_remove_history_text_history_diff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
