# Generated by Django 5.0.1 on 2024-09-24 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('profiles', '0019_alter_section_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_table_fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Наименование')),
                ('field', models.CharField(verbose_name='Транскрипция')),
                ('pos', models.PositiveIntegerField(default=100, verbose_name='Позиция')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_fields_manager_content_type', to='contenttypes.contenttype', verbose_name='Приложение')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_fields_manager_section', to='profiles.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Отображаемемое поле в выбранной таблице',
                'verbose_name_plural': 'Отображаемые поля в выбранных таблицах',
            },
        ),
    ]
