# Generated by Django 5.0.1 on 2024-10-10 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('table_fields_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_table_fields',
            name='filter',
            field=models.BooleanField(default=False, verbose_name='Фильруемый'),
        ),
        migrations.AddField(
            model_name='main_table_fields',
            name='filter_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='table_fields_manager_filter_type', to='contenttypes.contenttype', verbose_name='Класс справочника'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main_table_fields',
            name='filter_custom_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Кастомные данные'),
        ),
        migrations.AddField(
            model_name='main_table_fields',
            name='filter_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Справочник'), (2, 'Кастомный')], null=True, verbose_name='Тип'),
        ),
    ]
