# Generated by Django 5.0.1 on 2024-10-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_fields_manager', '0003_main_table_fields_filter_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_table_fields',
            name='filter_config',
            field=models.JSONField(blank=True, help_text='\n    {\n        "mapping": {\n            "title1": "title"\n        },\n        "current_section": true\n    }\n    ', null=True, verbose_name='Настройки поля'),
        ),
    ]
