name: Docker Build and Test

# Триггер для запуска — push или pull request в ветку main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v2

      # Шаг 3: Сборка Docker-образа
      - name: Build the Docker image
        run: |
          docker build -t my-app:latest .

      # Шаг 4: Запуск Docker контейнера
      - name: Run Docker container
        run: |
          docker run -d --name my-app-container my-app:latest

      # Шаг 5: Запуск тестов внутри контейнера
      - name: Run tests
        run: |
          docker exec my-app-container python3 manage.py test apps

      # Шаг 6: Остановка контейнера и очистка ресурсов
      - name: Clean up
        run: |
          docker stop my-app-container
          docker rm my-app-container
